"""Detection report service."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Dict

from dac.schemas.results import build_result
from dac.services.artifacts import write_result_artifact
from dac.services.paths import artifacts_dir, repo_root


def count_rules_by_category(sigma_rules_dir: Path) -> Dict[str, int]:
    """Count Sigma rules per category directory."""
    categories: Dict[str, int] = {}
    if not sigma_rules_dir.exists():
        return categories

    for category_dir in sigma_rules_dir.iterdir():
        if category_dir.is_dir():
            count = len(list(category_dir.glob("*.yml")) + list(category_dir.glob("*.yaml")))
            if count > 0:
                categories[category_dir.name] = count
    return categories


def count_converted_queries(output_dir: Path, backend: str) -> int:
    """Count generated backend query files."""
    backend_dir = output_dir / backend
    if not backend_dir.exists():
        return 0
    return len(
        [
            f
            for f in backend_dir.rglob(f"*.{backend}")
            if not f.name.endswith(".meta") and not f.name.endswith(".error")
        ]
    )


def generate_report(report_path: str = "output/report.md", artifact_output: str | None = None) -> Dict[str, object]:
    """Generate markdown report plus structured JSON summary."""
    rr = repo_root()
    sigma_dir = rr / "sigma-rules"
    output_dir = rr / "output"
    report_file = (rr / report_path).resolve() if not Path(report_path).is_absolute() else Path(report_path)

    output_dir.mkdir(parents=True, exist_ok=True)
    report_file.parent.mkdir(parents=True, exist_ok=True)

    categories = count_rules_by_category(sigma_dir)
    total_rules = sum(categories.values())
    splunk_count = count_converted_queries(output_dir, "splunk")
    kql_count = count_converted_queries(output_dir, "kql")

    splunk_pct = (splunk_count / total_rules * 100.0) if total_rules else 0.0
    kql_pct = (kql_count / total_rules * 100.0) if total_rules else 0.0

    report_text = f"""# Detection as Code Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

- **Total Sigma Rules**: {total_rules}
- **Splunk Queries Generated**: {splunk_count}
- **KQL Queries Generated**: {kql_count}

## Rules by Category

"""
    for category, count in sorted(categories.items()):
        report_text += f"- **{category.capitalize()}**: {count} rules\n"

    report_text += f"""
## Conversion Status

- Splunk: {splunk_count}/{total_rules} rules converted ({splunk_pct:.1f}%)
- KQL: {kql_count}/{total_rules} rules converted ({kql_pct:.1f}%)

## Next Steps

1. Review generated queries in `output/splunk/` and `output/kql/`
2. Test queries in your SIEM environment
3. Deploy validated queries to production
4. Monitor detection effectiveness

---
*This report is automatically generated by the Detection as Code pipeline.*
"""
    report_file.write_text(report_text, encoding="utf-8")

    result = build_result(
        status="success",
        stage="reporting",
        backend="sigma",
        metrics={
            "total_rules": total_rules,
            "splunk_queries": splunk_count,
            "kql_queries": kql_count,
        },
        artifacts={"report_path": str(report_file)},
    )
    out = Path(artifact_output) if artifact_output else artifacts_dir(rr) / "reporting.json"
    write_result_artifact(result, out)
    return result
