# Reusable step template for installing Python dependencies
parameters:
  packages: 'sigma-cli ruamel.yaml pyyaml'

steps:
  - task: PowerShell@2
    displayName: 'Install Python dependencies'
    inputs:
      targetType: 'inline'
      script: |
        python -m pip install --upgrade pip
        pip install ${{ parameters.packages }}
