#!/usr/bin/env python3
"""
Generate a detection report summarizing all Sigma rules and their conversions.
"""
import os
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict, List

def count_rules_by_category(sigma_rules_dir: Path) -> Dict[str, int]:
    """Count rules by category."""
    categories = {}
    
    for category_dir in sigma_rules_dir.iterdir():
        if category_dir.is_dir():
            rule_count = len(list(category_dir.glob("*.yml")) + list(category_dir.glob("*.yaml")))
            if rule_count > 0:
                categories[category_dir.name] = rule_count
    
    return categories

def count_converted_queries(output_dir: Path, backend: str) -> int:
    """Count successfully converted queries."""
    backend_dir = output_dir / backend
    if not backend_dir.exists():
        return 0
    
    query_files = [
        f for f in backend_dir.rglob(f"*.{backend}")
        if not f.name.endswith('.meta') and not f.name.endswith('.error')
    ]
    return len(query_files)

def generate_report():
    """Generate the detection report."""
    base_dir = Path(__file__).parent.parent
    sigma_rules_dir = base_dir / "sigma-rules"
    output_dir = base_dir / "output"
    report_file = output_dir / "report.md"
    
    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Count rules by category
    categories = count_rules_by_category(sigma_rules_dir)
    total_rules = sum(categories.values())
    
    # Count converted queries
    splunk_count = count_converted_queries(output_dir, "splunk")
    kql_count = count_converted_queries(output_dir, "kql")
    
    # Generate report
    report = f"""# Detection as Code Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

- **Total Sigma Rules**: {total_rules}
- **Splunk Queries Generated**: {splunk_count}
- **KQL Queries Generated**: {kql_count}

## Rules by Category

"""
    
    for category, count in sorted(categories.items()):
        report += f"- **{category.capitalize()}**: {count} rules\n"
    
    report += f"""
## Conversion Status

- Splunk: {splunk_count}/{total_rules} rules converted ({splunk_count/total_rules*100:.1f}% if total > 0 else 0:.1f}%)
- KQL: {kql_count}/{total_rules} rules converted ({kql_count/total_rules*100:.1f}% if total > 0 else 0:.1f}%)

## Next Steps

1. Review generated queries in `output/splunk/` and `output/kql/`
2. Test queries in your SIEM environment
3. Deploy validated queries to production
4. Monitor detection effectiveness

---
*This report is automatically generated by the Detection as Code pipeline.*
"""
    
    # Write report
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"Report generated: {report_file}")
    print(f"\nSummary:")
    print(f"  Total Rules: {total_rules}")
    print(f"  Splunk Queries: {splunk_count}")
    print(f"  KQL Queries: {kql_count}")

if __name__ == "__main__":
    generate_report()
